version: '3'
services:
  #my-app:
  # image: ${docker-registry}/my-app:1.0
  # image: my-app:1-0
  # ports:
  #  - 3000:3000
  memories:
    # image: ${docker-registry}/my-app:1.0
    image: memories:1.0
    ports:
      - 3000:3000
    build: .
    depends_on: 
      - mongodb
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    #command: --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    build: .
    depends_on: 
      - mongodb
volumes:
  mongo-data:
    driver: local
